{% set name = "pytest-cython" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-cython-{{ version }}.tar.gz
  sha256: 7c17f1df93b512f6d7df418b27c70da797d446829c38921a0fece546ed8927cf

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pytest >=6,<8
    - python >=3.6

test:
  imports:
    - pytest_cython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lgpage/pytest-cython
  summary: A plugin for testing Cython extension modules
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/lgpage/pytest-cython

extra:
  recipe-maintainers:
    - lgpage
    - jonashaag
