{% set name = "pytest-cython" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-cython-{{ version }}.tar.gz
  sha256: 4264474a8a6a2801256ad80f03e96552bd96848ddbcc3f1a7e37d7fa9a494455

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - pytest >=8
    - python >=3.6

test:
  imports:
    - pytest_cython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lgpage/pytest-cython
  summary: A plugin for testing Cython extension modules
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/lgpage/pytest-cython

extra:
  recipe-maintainers:
    - lgpage
    - jonashaag
